openapi: "3.0.0"
info:
  version: 0.0.1
  title: CLOUD-XJDF
  description: The json flavour of XJDF
paths:
  /queue-status:
    post:
      summary: Queue Status Summary
      operationId: queueStatusOp
      tags:
        - "QueueStatus (Combined Endpoint)"
      responses:
        '200':
          description: "foo"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseQueueStatusXjmf"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/SignalQueueStatusXjmf"
                - $ref: "#/components/schemas/QueryQueueStatusXjmf"
  /queue-status/query:
    post:
      tags:
        - "QueueStatus (Separate Endpoints)"
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseQueueStatusXjmf"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryQueueStatusXjmf"
  /queue-status/signal:
    post:
      tags:
        - "QueueStatus (Separate Endpoints)"
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseQueueStatusXjmf"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignalQueueStatusXjmf"

components:
  schemas:
    SignalQueueStatusXjmf:
      type: object
      properties:
        Header:
          $ref: "#/components/schemas/Header"
        SignalQueueStatus:
          $ref: "#/components/schemas/SignalQueueStatus"
      required: [header]
    SignalQueueStatus:
      type: object
      properties:
        Header:
          $ref: "#/components/schemas/Header"
        Queue:
          $ref: "#/components/schemas/Queue"
      required: [Header, Queue]
    QueryQueueStatusXjmf:
      type: object
      properties:
        Header:
          $ref: "#/components/schemas/Header"
        QueueStatusParams:
          $ref: "#/components/schemas/QueueStatusParams"
    QueueStatusParams:
      type: object
    ResponseQueueStatusXjmf:
      type: object
      properties:
        Header:
          $ref: "#/components/schemas/Header"
        Queue:
          $ref: "#/components/schemas/Queue"
    Queue:
      type: object
      properties:
        QueueEntry:
          type: array
          items:
            $ref: "#/components/schemas/QueueEntry"
    Header:
      type: object
      properties:
        AgentName:
          type: string
          example: "Alces"
        AgentVersion:
          type: string
          example: "1.6 BLD 009"
        DeviceId:
          type: string
          format: nmtoken
          pattern: "^[a-zA-Z0-9._\\-:]*$"
          example: D14_63
    QueueEntry:
      type: object